class AllahName {
  final int number;
  final String arabic;
  final String transliteration;
  final String urduMeaning;
  final String englishMeaning;

  const AllahName({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.urduMeaning,
    required this.englishMeaning,
  });

  static const List<AllahName> allNames = [
    AllahName(number: 1, arabic: 'الرَّحْمَٰنُ', transliteration: 'Ar-Rahman', urduMeaning: 'بے حد رحم کرنے والا', englishMeaning: 'The Most Gracious'),
    AllahName(number: 2, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Raheem', urduMeaning: 'نہایت مہربان', englishMeaning: 'The Most Merciful'),
    AllahName(number: 3, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', urduMeaning: 'حقیقی بادشاہ', englishMeaning: 'The King and Owner of All'),
    AllahName(number: 4, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', urduMeaning: 'ہر عیب سے پاک', englishMeaning: 'The Absolutely Pure'),
    AllahName(number: 5, arabic: 'السَّلَامُ', transliteration: 'As-Salam', urduMeaning: 'سلامتی دینے والا', englishMeaning: 'The Source of Peace'),
    AllahName(number: 6, arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mu\'min', urduMeaning: 'امان دینے والا', englishMeaning: 'The Giver of Faith and Security'),
    AllahName(number: 7, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', urduMeaning: 'نگہبان', englishMeaning: 'The Guardian'),
    AllahName(number: 8, arabic: 'الْعَزِيزُ', transliteration: 'Al-Azeez', urduMeaning: 'غالب اور زبردست', englishMeaning: 'The All-Mighty'),
    AllahName(number: 9, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', urduMeaning: 'زبردست', englishMeaning: 'The Compeller'),
    AllahName(number: 10, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', urduMeaning: 'بزرگی والا', englishMeaning: 'The Supreme'),
    AllahName(number: 11, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', urduMeaning: 'پیدا کرنے والا', englishMeaning: 'The Creator'),
    AllahName(number: 12, arabic: 'الْبَارِئُ', transliteration: 'Al-Bari\'', urduMeaning: 'ٹھیک بنانے والا', englishMeaning: 'The Maker of Order'),
    AllahName(number: 13, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', urduMeaning: 'صورت گری کرنے والا', englishMeaning: 'The Fashioner'),
    AllahName(number: 14, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', urduMeaning: 'بہت بخشنے والا', englishMeaning: 'The All-Forgiving'),
    AllahName(number: 15, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', urduMeaning: 'سب پر غالب', englishMeaning: 'The Subduer'),
    AllahName(number: 16, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', urduMeaning: 'بہت عطا کرنے والا', englishMeaning: 'The Supreme Bestower'),
    AllahName(number: 17, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', urduMeaning: 'رزق دینے والا', englishMeaning: 'The Provider'),
    AllahName(number: 18, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', urduMeaning: 'مشکل کشا', englishMeaning: 'The Opener'),
    AllahName(number: 19, arabic: 'الْعَلِيمُ', transliteration: 'Al-Aleem', urduMeaning: 'سب کچھ جاننے والا', englishMeaning: 'The All-Knowing'),
    AllahName(number: 20, arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', urduMeaning: 'تنگ کرنے والا', englishMeaning: 'The Withholder'),
    AllahName(number: 21, arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', urduMeaning: 'کشادہ کرنے والا', englishMeaning: 'The Extender'),
    AllahName(number: 22, arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', urduMeaning: 'پست کرنے والا', englishMeaning: 'The Reducer'),
    AllahName(number: 23, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi\'', urduMeaning: 'بلند کرنے والا', englishMeaning: 'The Exalter'),
    AllahName(number: 24, arabic: 'الْمُعِزُّ', transliteration: 'Al-Mu\'izz', urduMeaning: 'عزت دینے والا', englishMeaning: 'The Bestower of Honor'),
    AllahName(number: 25, arabic: 'الْمُذِلُّ', transliteration: 'Al-Muzill', urduMeaning: 'ذلت دینے والا', englishMeaning: 'The Dishonorer'),
    AllahName(number: 26, arabic: 'السَّمِيعُ', transliteration: 'As-Samee\'', urduMeaning: 'سب کچھ سننے والا', englishMeaning: 'The All-Hearing'),
    AllahName(number: 27, arabic: 'الْبَصِيرُ', transliteration: 'Al-Baseer', urduMeaning: 'سب کچھ دیکھنے والا', englishMeaning: 'The All-Seeing'),
    AllahName(number: 28, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', urduMeaning: 'فیصلہ کرنے والا', englishMeaning: 'The Judge'),
    AllahName(number: 29, arabic: 'الْعَدْلُ', transliteration: 'Al-\'Adl', urduMeaning: 'انصاف کرنے والا', englishMeaning: 'The Utterly Just'),
    AllahName(number: 30, arabic: 'اللَّطِيفُ', transliteration: 'Al-Lateef', urduMeaning: 'نرم خو / باریک بین', englishMeaning: 'The Subtle One'),
    AllahName(number: 31, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabeer', urduMeaning: 'خبر رکھنے والا', englishMeaning: 'The All-Aware'),
    AllahName(number: 32, arabic: 'الْحَلِيمُ', transliteration: 'Al-Haleem', urduMeaning: 'بردبار', englishMeaning: 'The Most Forbearing'),
    AllahName(number: 33, arabic: 'الْعَظِيمُ', transliteration: 'Al-Azeem', urduMeaning: 'عظمت والا', englishMeaning: 'The Magnificent'),
    AllahName(number: 34, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafoor', urduMeaning: 'معاف کرنے والا', englishMeaning: 'The Exceedingly Forgiving'),
    AllahName(number: 35, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakoor', urduMeaning: 'قدردان', englishMeaning: 'The Most Appreciative'),
    AllahName(number: 36, arabic: 'الْعَلِيُّ', transliteration: 'Al-Aliyy', urduMeaning: 'عالی شان', englishMeaning: 'The Most High'),
    AllahName(number: 37, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabeer', urduMeaning: 'سب سے بڑا', englishMeaning: 'The Most Great'),
    AllahName(number: 38, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafeez', urduMeaning: 'حفاظت کرنے والا', englishMeaning: 'The Preserver'),
    AllahName(number: 39, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqeet', urduMeaning: 'روزی دینے والا', englishMeaning: 'The Sustainer'),
    AllahName(number: 40, arabic: 'الْحَسِيبُ', transliteration: 'Al-Haseeb', urduMeaning: 'حساب لینے والا', englishMeaning: 'The Reckoner'),
    AllahName(number: 41, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jaleel', urduMeaning: 'بزرگ', englishMeaning: 'The Majestic'),
    AllahName(number: 42, arabic: 'الْكَرِيمُ', transliteration: 'Al-Kareem', urduMeaning: 'کرم کرنے والا', englishMeaning: 'The Most Generous'),
    AllahName(number: 43, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqeeb', urduMeaning: 'نگران', englishMeaning: 'The Watchful'),
    AllahName(number: 44, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujeeb', urduMeaning: 'دعا قبول کرنے والا', englishMeaning: 'The Responsive'),
    AllahName(number: 45, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi\'', urduMeaning: 'کشائش والا', englishMeaning: 'The All-Encompassing'),
    AllahName(number: 46, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakeem', urduMeaning: 'حکمت والا', englishMeaning: 'The All-Wise'),
    AllahName(number: 47, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadood', urduMeaning: 'محبت کرنے والا', englishMeaning: 'The Loving One'),
    AllahName(number: 48, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majeed', urduMeaning: 'بزرگی والا', englishMeaning: 'The Glorious'),
    AllahName(number: 49, arabic: 'الْبَاعِثُ', transliteration: 'Al-Ba\'ith', urduMeaning: 'مردوں کو اٹھانے والا', englishMeaning: 'The Resurrecter'),
    AllahName(number: 50, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shaheed', urduMeaning: 'حاضر و ناظر', englishMeaning: 'The All-Witnessing'),
    AllahName(number: 51, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', urduMeaning: 'سچا', englishMeaning: 'The Absolute Truth'),
    AllahName(number: 52, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakeel', urduMeaning: 'کارساز', englishMeaning: 'The Trustee'),
    AllahName(number: 53, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawiyy', urduMeaning: 'طاقتور', englishMeaning: 'The All-Strong'),
    AllahName(number: 54, arabic: 'الْمَتِينُ', transliteration: 'Al-Mateen', urduMeaning: 'مضبوط', englishMeaning: 'The Firm One'),
    AllahName(number: 55, arabic: 'الْوَلِيُّ', transliteration: 'Al-Waliyy', urduMeaning: 'دوست و مددگار', englishMeaning: 'The Protecting Associate'),
    AllahName(number: 56, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hameed', urduMeaning: 'تعریف کے لائق', englishMeaning: 'The Praiseworthy'),
    AllahName(number: 57, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', urduMeaning: 'شمار کرنے والا', englishMeaning: 'The All-Enumerating'),
    AllahName(number: 58, arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi\'', urduMeaning: 'پہلی بار پیدا کرنے والا', englishMeaning: 'The Originator'),
    AllahName(number: 59, arabic: 'الْمُعِيدُ', transliteration: 'Al-Mu\'eed', urduMeaning: 'دوبارہ پیدا کرنے والا', englishMeaning: 'The Restorer'),
    AllahName(number: 60, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', urduMeaning: 'زندگی دینے والا', englishMeaning: 'The Giver of Life'),
    AllahName(number: 61, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumeet', urduMeaning: 'موت دینے والا', englishMeaning: 'The Bringer of Death'),
    AllahName(number: 62, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', urduMeaning: 'ہمیشہ زندہ رہنے والا', englishMeaning: 'The Ever-Living'),
    AllahName(number: 63, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyoom', urduMeaning: 'سب کو قائم رکھنے والا', englishMeaning: 'The Sustainer'),
    AllahName(number: 64, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', urduMeaning: 'پانے والا', englishMeaning: 'The Perceiver'),
    AllahName(number: 65, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', urduMeaning: 'عظمت والا', englishMeaning: 'The Illustrious'),
    AllahName(number: 66, arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', urduMeaning: 'ایک / اکیلا', englishMeaning: 'The One'),
    AllahName(number: 67, arabic: 'الْأَحَدُ', transliteration: 'Al-Ahad', urduMeaning: 'یکتا', englishMeaning: 'The Unique'),
    AllahName(number: 68, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', urduMeaning: 'بے نیاز', englishMeaning: 'The Eternal'),
    AllahName(number: 69, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', urduMeaning: 'قدرت والا', englishMeaning: 'The Omnipotent'),
    AllahName(number: 70, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', urduMeaning: 'پوری قدرت رکھنے والا', englishMeaning: 'The Powerful'),
    AllahName(number: 71, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', urduMeaning: 'آگے کرنے والا', englishMeaning: 'The Expediter'),
    AllahName(number: 72, arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Mu\'akkhir', urduMeaning: 'پیچھے کرنے والا', englishMeaning: 'The Delayer'),
    AllahName(number: 73, arabic: 'الْأَوَّلُ', transliteration: 'Al-Awwal', urduMeaning: 'سب سے پہلا', englishMeaning: 'The First'),
    AllahName(number: 74, arabic: 'الْآخِرُ', transliteration: 'Al-Akhir', urduMeaning: 'سب سے آخری', englishMeaning: 'The Last'),
    AllahName(number: 75, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', urduMeaning: 'ظاہر', englishMeaning: 'The Manifest'),
    AllahName(number: 76, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', urduMeaning: 'پوشیدہ', englishMeaning: 'The Hidden'),
    AllahName(number: 77, arabic: 'الْوَالِي', transliteration: 'Al-Wali', urduMeaning: 'مالک و کارساز', englishMeaning: 'The Governor'),
    AllahName(number: 78, arabic: 'الْمُتَعَالِي', transliteration: 'Al-Muta\'ali', urduMeaning: 'بلند تر', englishMeaning: 'The Supreme One'),
    AllahName(number: 79, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', urduMeaning: 'احسان کرنے والا', englishMeaning: 'The Source of All Goodness'),
    AllahName(number: 80, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', urduMeaning: 'توبہ قبول کرنے والا', englishMeaning: 'The Ever-Pardoning'),
    AllahName(number: 81, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', urduMeaning: 'بدلہ لینے والا', englishMeaning: 'The Avenger'),
    AllahName(number: 82, arabic: 'الْعَفُوُّ', transliteration: 'Al-\'Afuww', urduMeaning: 'معاف کرنے والا', englishMeaning: 'The Pardoner'),
    AllahName(number: 83, arabic: 'الرَّءُوفُ', transliteration: 'Ar-Ra\'oof', urduMeaning: 'شفقت کرنے والا', englishMeaning: 'The Most Kind'),
    AllahName(number: 84, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', urduMeaning: 'ملک کا مالک', englishMeaning: 'Master of the Kingdom'),
    AllahName(number: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَامِ', transliteration: 'Zul-Jalali wal-Ikram', urduMeaning: 'عظمت اور عزت والا', englishMeaning: 'Lord of Majesty and Generosity'),
    AllahName(number: 86, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', urduMeaning: 'انصاف کرنے والا', englishMeaning: 'The Equitable'),
    AllahName(number: 87, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami\'', urduMeaning: 'جمع کرنے والا', englishMeaning: 'The Gatherer'),
    AllahName(number: 88, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghaniyy', urduMeaning: 'بے پرواہ / غنی', englishMeaning: 'The Self-Sufficient'),
    AllahName(number: 89, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', urduMeaning: 'غنی کرنے والا', englishMeaning: 'The Enricher'),
    AllahName(number: 90, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani\'', urduMeaning: 'روکنے والا', englishMeaning: 'The Withholder'),
    AllahName(number: 91, arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', urduMeaning: 'نقصان پہنچانے والا', englishMeaning: 'The Distresser'),
    AllahName(number: 92, arabic: 'النَّافِعُ', transliteration: 'An-Nafi\'', urduMeaning: 'نفع پہنچانے والا', englishMeaning: 'The Propitiator'),
    AllahName(number: 93, arabic: 'النُّورُ', transliteration: 'An-Noor', urduMeaning: 'نور', englishMeaning: 'The Light'),
    AllahName(number: 94, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', urduMeaning: 'ہدایت دینے والا', englishMeaning: 'The Guide'),
    AllahName(number: 95, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badee\'', urduMeaning: 'انوکھا بنانے والا', englishMeaning: 'The Incomparable Originator'),
    AllahName(number: 96, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', urduMeaning: 'ہمیشہ رہنے والا', englishMeaning: 'The Everlasting'),
    AllahName(number: 97, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', urduMeaning: 'وارث', englishMeaning: 'The Inheritor'),
    AllahName(number: 98, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rasheed', urduMeaning: 'ہدایت والا', englishMeaning: 'The Guide to the Right Path'),
    AllahName(number: 99, arabic: 'الصَّبُورُ', transliteration: 'As-Saboor', urduMeaning: 'صبر کرنے والا', englishMeaning: 'The Most Patient'),
  ];
}
